### ISSUE TITLE
move -Xmx5g after java keyword

### ISSUE THREAD

**Issue by EricFournier3** [sgsutcliffe/Wastewater_Analysis_Pipeline#5]
https://github.com/sgsutcliffe/Wastewater_Analysis_Pipeline/blob/6e0437f43278bb270f0eec276783bbfaf3755aa1/QC_parallelization_V2.py#L44

**Comment by EricFournier3** [comment]
same for line 50

**Comment by sgsutcliffe** [comment]
I had scrapped Picard from my QC-pipeline because I couldn’t get it to work. If this fixes it let me know, I can bring it back in my next version.

**Comment by EricFournier3** [comment]
its working for me
